server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:9088/motel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094

  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2000MB
      file-size-threshold: 2KB
  data:
    redis:
      port: 6379
      host: localhost

cloudinary:
  cloud-name: ${CLOUD-NAME}
  api-key: ${API-KEY-CLOUDINARY}
  api-secret: ${API-SECRET-KEY-CLOUDINARY}

jwt:
  secret-key: e2fd201b2b295395cebbf5f54adae4a742b13175
logging:
  level:
    org.springframework.security: DEBUG

